### ISSUE TITLE
ima_emulator defaults to STUB_TPM False

### ISSUE THREAD

**Issue by lukehinds** [mit-ll/python-keylime#16]
# Environment
 * OS / version: Fedora 28
 * Processor architecture: VM
 * TPM Manufacturer: IBM Emu
 * Keylime version: master

# Description 

When running ` tpm_emulator` as a service and installed via [ima_stub_service](https://github.com/mit-ll/python-keylime/tree/master/ima_stub_service), the service fails with the following traceback:

```
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]: Using config file /etc/keylime.conf
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]: Monitoring /sys/kernel/security/ima/ascii_runtime_measurements
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]: Traceback (most recent call last):
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]:   File "/usr/bin/keylime_ima_emulator", line 11, in <module>
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]:     load_entry_point('keylime==1.2', 'console_scripts', 'keylime_ima_emulator')()
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]:   File "/usr/lib64/python2.7/site-packages/keylime-1.2-py2.7-linux-x86_64.egg/keylime/ima_emulator_adapter.py", line 90, in main
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]:     fd_object = file(common.IMA_ML, "r")
Jan 03 14:23:45 localhost.localdomain tpm_with_ima.sh[3700]: IOError: [Errno 2] No such file or directory: '/sys/kernel/security/ima/ascii_runtime_measurements'
```

This is due to [STUB_IMA](https://github.com/mit-ll/python-keylime/blob/master/keylime/common.py#L81) being set to `False`, as it inherits from  [STUB_TPM](https://github.com/mit-ll/python-keylime/blob/master/keylime/common.py#L57), which is also `False`

As `STUB_IMA` is `False`, common.py sets `IMA_ML` as `/sys/kernel/security/ima/ascii_runtime_measurement` , as seen [here](https://github.com/mit-ll/python-keylime/blob/master/keylime/common.py#L336)

## Expected behavior vs. actual behavior 

When keylime_ima_emulator is used, IMA_ML should be set to use the canned data in `scripts/ima/ascii_runtime_measurements` 

Instead it ends up using `/sys/kernel/security/ima/ascii_runtime_measurements` which does not exist.

## Steps to reproduce problem
1. install tpm_emulator.service
2. Start tpm_emulator.service

I guess folks have been setting STUB_IMA in their IDE somehow. My recommendation is we expose it as a config value in `keylime.conf` as well.

**Comment by lukehinds** [comment]
Another possible solution is we use also query os.environ for the `STUB_IMA` boolean - I think I prefer this approach.

**Comment by nabilschear** [comment]
The flags in common.py are for developers and/or can put keylime into an insecure/unsafe state.  the intention behind not putting them into the conf file or to be set via env is to avoid someone accidentally activating one of these features and being insecure.  there may be a way to set those states correctly. You can run IMA with no tpm and use the ima_stub_service (an unfortunate re-use of the word stub) But we haven't figured out how to use STUB_TPM and the ima_stub_service at the same time.

**Comment by lukehinds** [comment]
Ah makes sense with that context. I will look into using with no tpm, might have to get back to you for some help on that.

In the meantime, let's close this one as invalid.

**Comment by nabilschear** [comment]
if you turn ima on in the kernel (ima_tcb on the kernel command line will do it), then it will populate the ascii_measurements file whether you have a tpm or not (or if you have one that is disabled or not activated).   the kernel just won't extend those measurements into pcr 10 on the tpm.
