### ISSUE TITLE
Keylime Install Script does not support CentOS

### ISSUE THREAD

**Issue by geedo0** [mit-ll/python-keylime#2]
# Environment
 * OS / version: CentOS
 * Processor architecture: x86_64
 * TPM Manufacturer: 
 * Keylime version: [Commit](https://github.com/mit-ll/python-keylime/commit/2e7716c1393116c8a39aa47989a0eecdfd07a3b2)

# Description 
The install script assumes that the user is running Ubuntu because it only runs apt commands. The corresponding yum commands are provided in the README so it should be a straightforward addition to add CentOS support.

## Expected behavior vs. actual behavior 
The installer exits prematurely when updating packages. It should install Keylime on CentOS successfully.

## Steps to reproduce problem
1. Run installer.sh on CentOS

**Comment by nabilschear** [comment]
this should be easy to add to our scripts.  we'll look at adding some if blocks for this

**Comment by jetwhiz** [comment]
The installer scripts have been updated and should work with both Debian-based and RH-based systems.  This fix will be available with the next Keylime release.
