### ISSUE TITLE
Change defaults to sha256

### ISSUE THREAD

**Issue by lukehinds** [mit-ll/python-keylime#26]
# Environment
 * OS / version: N/A
 * Processor architecture: N/A
 * TPM Manufacturer: N/A
 * Keylime version: master

# Description 

When the TPM 2.0 work is complete https://github.com/mit-ll/python-keylime/issues/5 and we have  "algorithm agility" we should change from using the current default of sha1 to sha256 (or stronger).

**Comment by jetwhiz** [comment]
Thanks, @lukehinds!  The default hash for TPM 2.0 can be configured in keylime.conf, and defaults to sha256
