### ISSUE TITLE
Performing GET request without API version prematurely terminates the connection

### ISSUE THREAD

**Issue by geedo0** [mit-ll/python-keylime#4]
# Environment
 * OS / version: Ubuntu 16.04
 * Processor architecture: x86_64
 * TPM Manufacturer: 
 * Keylime version: [Commit](https://github.com/mit-ll/python-keylime/commit/2e7716c1393116c8a39aa47989a0eecdfd07a3b2)

# Description 
If you do a GET without the /v2/ on any of the servers the connection drops immediately and you don't an HTTP response.

## Expected behavior vs. actual behavior 
The HTTP servers should return a valid HTTP error status and possibly a message indicating the missing API version.

## Steps to reproduce problem
1. Start up the cloud verifier or registrar.
1. Send a ```curl --get localhost:{registrar,verifier}port/anything```

# Relevant logs
```
geedo@sc-airlock:~$ curl --get http://localhost:8890/asdf
curl: (52) Empty reply from server
```

**Comment by jetwhiz** [comment]
Hi @geedo0 -- this has now been taken care of and will be fixed in the next release
