### ISSUE TITLE
Add TPM 2.0 Support to Keylime

### ISSUE THREAD

**Issue by jetwhiz** [mit-ll/python-keylime#5]
Keylime currently uses IBM tpm4720 with TPM 1.2 support, which is not compatible with the new and improved TPM 2.0 standard.  

We should examine the effort required to add TPM 2.0 support to Keylime.

**Comment by nabilschear** [comment]
IBM also has a tpm 2.0 library that works in much the same manner as the version used in keylime.  this could be the easiest port option.  https://sourceforge.net/projects/ibmtpm20tss/ . Instead of looking at the Intel TPM 2.0 stack

**Comment by lukehinds** [comment]
Did you folks manage to get started on this?

If not already under way, its worth considering tpm-tss software stack. It might take a bit more work and not as easily swap'outable, but would be worth it in the long run. tpm-tss is under very active development , has a good varied amount of contributors and has greater coverage of features exposed in the TPM. It also also packaged in all of the major distributions (debian / rhel famlies and OpenSUSE). In fact it is supported by Red Hat on production systems [0] 

The other useful factor is it works in-conjunction with a resource and broker manager (tpm2-abrmd_ and a CLI toolset (tpm-tools)

[0] https://access.redhat.com/errata/RHEA-2017:2245
